apiVersion: v1
kind: Pod
metadata:
  name: angularpoc-pod
  labels:
    name: angularpoc
spec:
  containers:
    - image: 192.168.2.15:10082/angularpoc:latest
      name: angularpoc
      imagePullPolicy: Always
  imagePullSecrets:
    - name: nexus